name: pdearena
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asciitree=0.3.3=py_2
  - blas=1.0=mkl
  - bokeh=2.4.3=py38h06a4308_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask=2022.7.0=py38h06a4308_0
  - dask-core=2022.7.0=py38h06a4308_0
  - distributed=2022.7.0=py38h06a4308_0
  - fasteners=0.16.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - h5py=3.7.0=py38h737f45e_0
  - hdf5=1.10.6=h3ffc7dd_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - locket=1.0.0=py38h06a4308_0
  - lz4=3.1.3=py38h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - msgpack-python=1.0.3=py38hd09550d_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - numcodecs=0.9.1=py38h295c915_0
  - numexpr=2.8.3=py38h807cd23_0
  - numpy=1.23.1=py38h6c91a56_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py38h6a678d5_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.2.2=py38h06a4308_0
  - portalocker=2.3.0=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py38h06a4308_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py38h06a4308_0
  - setuptools=63.4.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.39.3=h5082296_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py38_cu113
  - torchdata=0.4.1=py38
  - torchvision=0.13.1=py38_cu113
  - tornado=6.1=py38h27cfd23_0
  - typing-extensions=4.3.0=py38h06a4308_0
  - typing_extensions=4.3.0=py38h06a4308_0
  - urllib3=1.26.11=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xarray=0.20.1=pyhd3eb1b0_1
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zarr=2.8.1=pyhd3eb1b0_0
  - zict=2.1.0=py38h06a4308_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.3.0
      - aiohttp==3.8.3
      - aiosignal==1.2.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.2
      - attrs==22.1.0
      - cachetools==5.2.0
      - commonmark==0.9.1
      - contourpy==1.0.5
      - cycler==0.11.0
      - decorator==5.1.1
      - docstring-parser==0.15
      - fonttools==4.37.4
      - frozenlist==1.3.1
      - fsspec==2022.8.2
      - gcsfs==2022.8.2
      - google-api-core==2.10.2
      - google-auth==2.12.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-core==2.3.2
      - google-cloud-storage==2.5.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.4.0
      - googleapis-common-protos==1.56.4
      - grpcio==1.49.1
      - hydra-core==1.2.0
      - importlib-metadata==5.0.0
      - importlib-resources==5.10.0
      - jsonargparse==4.15.1
      - kiwisolver==1.4.4
      - markdown==3.4.1
      - matplotlib==3.6.1
      - multidict==6.0.2
      - oauthlib==3.2.1
      - omegaconf==2.2.3
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydeprecate==0.3.2
      - pygments==2.13.0
      - pytorch-lightning==1.7.7
      - pyyaml==6.0
      - requests-oauthlib==1.3.1
      - rich==12.6.0
      - rsa==4.9
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - torchmetrics==0.10.0
      - torchtext==0.13.1
      - tqdm==4.64.1
      - werkzeug==2.2.2
      - yarl==1.8.1
      - zipp==3.9.0
